//
// Created by evgen on 28.04.2026.
//

#ifndef ELECTROMAGNETIC_WAVES_SCATTERING_SQUAREQUADRATUREPOINTS_HPP
#define ELECTROMAGNETIC_WAVES_SCATTERING_SQUAREQUADRATUREPOINTS_HPP



#endif // ELECTROMAGNETIC_WAVES_SCATTERING_SQUAREQUADRATUREPOINTS_HPP
