//
// Created by evgen on 25.01.24.
//

#ifndef ELECTROMAGNETIC_WAVES_SCATTERING_OBJPARSER_H
#define ELECTROMAGNETIC_WAVES_SCATTERING_OBJPARSER_H



#endif //ELECTROMAGNETIC_WAVES_SCATTERING_OBJPARSER_H
