//
// Created by evgen on 25.01.24.
//

#ifndef ELECTROMAGNETIC_WAVES_SCATTERING_INTEGRATED2D_H
#define ELECTROMAGNETIC_WAVES_SCATTERING_INTEGRATED2D_H



#endif //ELECTROMAGNETIC_WAVES_SCATTERING_INTEGRATED2D_H
